version: '4'

services:
  ### Postgres database for ApiRest
  db-books:
    container_name: db-books
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_books
      POSTGRES_USER: metacho
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command:
      -p 5432